apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: presentium-api
    app.kubernetes.io/component: api-server
    app.kubernetes.io/instance: presentium-{{ .Values.global.instance }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/part-of: presentium
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
