#!/bin/sh

echo '[git hook] executing gradle spotlessCheck before commit'

# Gather the staged files - to make sure changes are saved only for these files.
STAGED_FILES=$(git diff --staged --name-only)

# run spotless apply
./gradlew spotlessApply

STATUS=$?

if [ "$STATUS" = 0 ] ; then
    echo "Static analysis found no problems."
    # Add staged file changes to git
    for file in $STAGED_FILES; do
      if test -f "$file"; then
        git add $file
      fi
    done
    #Exit
    exit 0
else
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "Spotless Apply found violations it could not fix."
    echo "Run spotless apply in your terminal and fix the issues before trying to commit again."
    echo "       ********************************************      "
    echo "*********************************************************"
    #Exit
    exit 1
fi
